// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmqhkyagztngzfnuuujm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tcWhreWFnenRuZ3pmbnV1dWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDk1MjIsImV4cCI6MjA2NDEyNTUyMn0.FJBWSBObAEA5q95aU8LM59VhJ_Owr-7KK2JhUIsfPUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);